### ISSUE TITLE
Various requests and LIG bug

### ISSUE THREAD

**Issue by rpryzant** [cdpierse/transformers-interpret#26]
This package is amazing!! Thank you so much for putting it together. I had a hard time using it though and noticed a few issues of issues (detailed below) that made me eventually drop it in favor of writing my own abstractions, so I believe this feedback, if incorporated, would make your package much more helpful and popular for others! So sorry for dumping all of these issues/feature requests on you without putting in some pull requests myself but I hope it's useful :) 

1. I think this was the biggest issue for me, the interface is confusingly split across an object (`SequenceClassificationExplainer`) that also acts as a quasi-factory method. The constructor and instance also overlap in their functionality, e.g. my understanding is that there's two ways to attribute a bunch of texts:
```
    for text, label in zip(texts, labels):
        explainer = SequenceClassificationExplainer(text, model, tokenizer)
        attributions = explainer(index=1)
        print(attributions.word_attributions)             # note how the products of the inference/attribution live in two different objects
        print(cls_explainer.predicted_class_index)
```
or, equivalently 
```
    explainer = SequenceClassificationExplainer("",  model, tokenizer)
    for text, label in zip(texts, labels):
        attributions = explainer(text= text, index=1)
        print(attributions.word_attributions)             # products of the inference/attribution still live in two different objects?
        print(cls_explainer.predicted_class_index)
```

I think it might be much cleaner to have one object which is in charge of orchestrating the attribution!
```
    explainer = SequenceClassificationExplainer(model, tokenizer)    
    for text, label in zip(texts, labels):
        attributions = explainer.explain(text= text, index=1)
        print(attributions.word_attributions)             # products of the inference/attribution live in same object
        print(attributions.predicted_class_index)
```

2.  `true_class` in `visualize()` is expected to be a string, but immediately cast to an int https://github.com/cdpierse/transformers-interpret/blob/2e41a6b518f12e67697213764c7921398f9d016d/transformers_interpret/explainers/sequence_classification.py#L110

3. I think there's a bug in how you're calling LIG? I think using the input_ids as a baseline is bad because then there's nothing for LIG to interpolate between when computing gradients. I'm less sure about the token type ids but I think the preferred approach is just giving it the special tokens and pads as your baseline.

https://github.com/cdpierse/transformers-interpret/blob/deebcf8e109ef405a6cf52e5f0e102be2bda45b1/transformers_interpret/attributions.py#L54

4. Argument "text" goes unused
https://github.com/cdpierse/transformers-interpret/blob/deebcf8e109ef405a6cf52e5f0e102be2bda45b1/transformers_interpret/attributions.py#L99

5. It would be nice if `cls_explainer.visualize()` optionally wrote to a file and instead returned the HTML so the user could decide what to do with it. 

Again, thank you so much for putting this together and hope this is useful for you!

**Comment by cdpierse** [comment]
Hi @rpryzant, 

Thank you very much for the suggestions and input, this package is super nascent at the moment and there are a lot of things I would like to change going forward with it many of which you have mentioned here. I'm going to address each of your comments point by point as I think that's easiest:

1.  Totally in agreement on this, it's my biggest issue with the package at the moment aswell especially since I've been working on a question answering explainer and the design of the constructor has kind of started to fall apart. I'm going to separate the constructor from the instantiated object. At the time I guess I really liked the idea of a one liner but it doesn't really work well and the two behaviors are confusing. 
 
The only change I would make to the example you provided is that I would try and keep the instance of the explainer as a callable rather than invoking a `explain` method, I would be interested though in why you would do it this way. Also when you refer to the products of the inference and attribution living in the same versus different object I couldn't see a significant difference between your first and last example other than text being a required argument to the explain method. 

This is how I would go about structuring the interface:

``` python
    explainer = SequenceClassificationExplainer(model, tokenizer)    
    for text, label in zip(texts, labels):
        attributions = explainer(text= text, index=1)
        print(attributions.word_attributions)            
        print(attributions.predicted_class_index)
```

2.  You're right I think this is a layover of an old bug I was having with the visualizer where I was casting everything to string for safety. I'm doing two different behaviors here for models of different types i.e. models that have a single node output are having the class cast to a int (either 0 or 1) whereas models that have multi-node ouputs have the true class cast to a string. I'll definitely fix this although I don't think it should be causing any major issues as the type casting here is purely cosmetic. 

3. I think you be incorrect here, from what I can see I am using `ref_input_ids` which is special tokens plus pads for attributions, when token type ids and position ids are available I also use their reference type ids as well. The team at Captum  were very helpful recently in helping me figure out how to pass reference ids for token type and position ids you can check that out here pytorch/captum#624
4. Yep it does, that's probably going to go in the next update. 
5. The latest version should be returning the iPython HTML object in `visualize`, writing to a file has been optional from the start I believe. 

Thank you again for this input, I really appreciate it especially at this stage of the project, I think it has a lot of room to grow but I need to figure out interface issues like those you have highlighted first. Would love to hear any other suggestions you might have in the future.
